name: circulor-mkdocs

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: build
        run: make docker-build
      # - name: login
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      #     AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      #     AWS_REGION: ${{secrets.AWS_REGION}}
      #   run: make docker-login
      # - name: push
      #   run: make docker-push


